name: Build Android
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn

      - name: Build Android Release
        run: |
          npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: android/app/build/outputs/apk/release/*.apk
